apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment # <--- THIS LINE IS CRUCIAL AND MUST BE PRESENT AND CORRECTLY INDENTED
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hw-container
        image: ayushijainn111/app1-k8s:latest
        ports:
        - containerPort: 5000